name: clone repositories

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  clone-submodules:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
        with:
          repository: MichaelGrafnetter/DSInternals
          path: DSInternals
      - uses: actions/checkout@v2
      - run: |
          git submodule add https://github.com/MichaelGrafnetter/DSInternals.git DSInternals
        continue-on-error: true    
      
      - uses: actions/checkout@v2
        with:
          repository: sqlmapproject/sqlmap
          path: sqlmap
      - uses: actions/checkout@v2
      - run: |   
          git submodule add https://github.com/sqlmapproject/sqlmap.git sqlmap
        continue-on-error: true     
      
      - uses: actions/checkout@v2
        with:
          repository: SnaffCon/Snaffler
          path: Snaffler
      - uses: actions/checkout@v2
      - run: |   
          git submodule add https://github.com/SnaffCon/Snaffler.git Snaffler
        continue-on-error: true
        
      - uses: actions/checkout@v2
        with:
          repository: bitsadmin/wesng
          path: wesng    
      - uses: actions/checkout@v2
      - run: |    
          git submodule add https://github.com/bitsadmin/wesng.git wesng
        continue-on-error: true   
            
      - uses: actions/checkout@v2
        with:
          repository: wagga40/Zircolite
          path: Zircolite
      - uses: actions/checkout@v2
      - run: |     
          git submodule add https://github.com/wagga40/Zircolite.git Zircolite
        continue-on-error: true   
      
      - uses: actions/checkout@v2
        with:
          repository: VirusTotal/yara
          path: yara
      - uses: actions/checkout@v2
      - run: |       
          git submodule add https://github.com/VirusTotal/yara.git yara
        continue-on-error: true     
      
      - uses: actions/checkout@v2
      - run: |
          git config user.name liranpi2
          git add .
          git commit -m "add submodule"
          git push
